# Generated by Django 5.1.5 on 2025-02-02 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('time', models.TimeField(verbose_name='start time')),
                ('action', models.CharField(max_length=255, verbose_name='action')),
                ('is_enjoyable', models.BooleanField(default=False, verbose_name='is enjoyable')),
                ('frequency', models.IntegerField(default=1, verbose_name='frequency (in days, 1 = daily, 2 = every 2 days, not more than 7 days)')),
                ('reward', models.CharField(max_length=255, verbose_name='reward')),
                ('time_required', models.IntegerField(verbose_name='required time (in seconds, maximum 120)')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='habit_builder')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='related habit')),
            ],
            options={
                'verbose_name': 'habit',
                'verbose_name_plural': 'habits',
                'ordering': ('id',),
            },
        ),
    ]
